"""
Value maps from config-metadata-switching application.yml.
Display labels and codes -> canonical stored value. Do not edit by hand;
regenerate from application.yml when metadata changes.
"""
from __future__ import annotations

import unicodedata
from typing import Any, Dict, FrozenSet, List, Tuple

# (canonical value, display label) per metadata element
ELEMENT_ENTRIES: Dict[str, List[Tuple[str, str]]] = {
    "address_type": [
        ("P", "Physical"),
        ("B", "Billing"),
    ],
    "authorization_type": [
        ("OIDC", "OIDC"),
        ("OAUTH 2.0", "OAUTH 2.0"),
        ("SAML 2.0", "SAML 2.0"),
        ("JWT", "JWT Token"),
        ("WSDL", "WSDL"),
    ],
    "connection_type": [
        ("SOAP", "SOAP over HTTP/HTTPS"),
        ("TCP/IP", "TCP/IP"),
        ("REST", "REST"),
        ("gRPC", "gRPC"),
    ],
    "connector_id": [
        ("guga-connector", "Guga Connector"),
        ("postilian-connector", "Postilian Connector"),
    ],
    "connector_service_id": [
        ("switch-rest-connector-guga.switching.svc.cluster.local", "Guga Connector Service"),
        ("postilian-connector.switching.svc.cluster.local", "Postilian Connector Service"),
    ],
    "connector_transaction_type": [
        ("1", "Corresponsalia"),
        ("3", "Cards"),
    ],
    "connector_type": [
        ("IN", "Inward"),
        ("OUT", "Outward"),
    ],
    "country_code_all": [
        ("AFG", "Afghanistan (AFG)"),
        ("ALA", "Aland Islands (ALA)"),
        ("ALB", "Albania (ALB)"),
        ("DZA", "Algeria (DZA)"),
        ("ASM", "American Samoa (ASM)"),
        ("AND", "Andorra (AND)"),
        ("AGO", "Angola (AGO)"),
        ("AIA", "Anguilla (AIA)"),
        ("ATA", "Antarctica (ATA)"),
        ("ATG", "Antigua and Barbuda (ATG)"),
        ("ARG", "Argentina (ARG)"),
        ("ARM", "Armenia (ARM)"),
        ("ABW", "Aruba (ABW)"),
        ("AUS", "Australia (AUS)"),
        ("AUT", "Austria (AUT)"),
        ("AZE", "Azerbaijan (AZE)"),
        ("BHS", "Bahamas (the) (BHS)"),
        ("BHR", "Bahrain (BHR)"),
        ("BGD", "Bangladesh (BGD)"),
        ("BRB", "Barbados (BRB)"),
        ("BLR", "Belarus (BLR)"),
        ("BEL", "Belgium (BEL)"),
        ("BLZ", "Belize (BLZ)"),
        ("BEN", "Benin (BEN)"),
        ("BMU", "Bermuda (BMU)"),
        ("BTN", "Bhutan (BTN)"),
        ("BOL", "Bolivia (BOL)"),
        ("BES", "Bonaire Sint Eustatius Saba (BES)"),
        ("BIH", "Bosnia and Herzegovina (BIH)"),
        ("BWA", "Botswana (BWA)"),
        ("BVT", "Bouvet Island (BVT)"),
        ("BRA", "Brazil (BRA)"),
        ("IOT", "British Indian Ocean Territory (the) (IOT)"),
        ("BRN", "Brunei Darussalam (BRN)"),
        ("BGR", "Bulgaria (BGR)"),
        ("BFA", "Burkina Faso (BFA)"),
        ("BDI", "Burundi (BDI)"),
        ("CPV", "Cabo Verde (CPV)"),
        ("KHM", "Cambodia (KHM)"),
        ("CMR", "Cameroon (CMR)"),
        ("CAN", "Canada (CAN)"),
        ("CYM", "Cayman Islands (CYM)"),
        ("CAF", "Central African Republic (the) (CAF)"),
        ("TCD", "Chad (TCD)"),
        ("CHL", "Chile (CHL)"),
        ("CHN", "China (CHN)"),
        ("CXR", "Christmas Island (CXR)"),
        ("CCK", "Cocos (Keeling) Islands (the) (CCK)"),
        ("COL", "Colombia (COL)"),
        ("COM", "Comoros (the) (COM)"),
        ("COD", "Congo (the) (COD)"),
        ("COK", "Cook Islands (the) (COK)"),
        ("CRI", "Costa Rica (CRI)"),
        ("CIV", "Cote d'Ivoire (CIV)"),
        ("HRV", "Croatia (HRV)"),
        ("CUB", "Cuba (CUB)"),
        ("CUW", "Curaçao (CUW)"),
        ("CYP", "Cyprus (CYP)"),
        ("CZE", "Czechia (CZE)"),
        ("DNK", "Denmark (DNK)"),
        ("DJI", "Djibouti (DJI)"),
        ("DMA", "Dominica (DMA)"),
        ("DOM", "Dominican Republic (the) (DOM)"),
        ("ECU", "Ecuador (ECU)"),
        ("EGY", "Egypt (EGY)"),
        ("SLV", "El Salvador (SLV)"),
        ("GNQ", "Equatorial Guinea (GNQ)"),
        ("ERI", "Eritrea (ERI)"),
        ("EST", "Estonia (EST)"),
        ("SWZ", "Eswatini (SWZ)"),
        ("ETH", "Ethiopia (ETH)"),
        ("FLK", "Falkland Islands (the) (FLK)"),
        ("FRO", "Faroe Islands (the) (FRO)"),
        ("FJI", "Fiji (FJI)"),
        ("FIN", "Finland (FIN)"),
        ("FRA", "France (FRA)"),
        ("GUF", "French Guiana (GUF)"),
        ("PYF", "French Polynesia (PYF)"),
        ("ATF", "French Southern Territories (ATF)"),
        ("GAB", "Gabon (GAB)"),
        ("GMB", "Gambia (the) (GMB)"),
        ("GEO", "Georgia (GEO)"),
        ("DEU", "Germany (DEU)"),
        ("GHA", "Ghana (GHA)"),
        ("GIB", "Gibraltar (GIB)"),
        ("GRC", "Greece (GRC)"),
        ("GRL", "Greenland (GRL)"),
        ("GRD", "Grenada (GRD)"),
        ("GLP", "Guadeloupe (GLP)"),
        ("GUM", "Guam (GUM)"),
        ("GTM", "Guatemala (GTM)"),
        ("GGY", "Guernsey (GGY)"),
        ("GIN", "Guinea (GIN)"),
        ("GNB", "Guinea-Bissau (GNB)"),
        ("GUY", "Guyana (GUY)"),
        ("HTI", "Haiti (HTI)"),
        ("HMD", "Heard Island and McDonald Islands (HMD)"),
        ("VAT", "Holy See (the) (VAT)"),
        ("HND", "Honduras (HND)"),
        ("HKG", "Hong Kong (HKG)"),
        ("HUN", "Hungary (HUN)"),
        ("ISL", "Iceland (ISL)"),
        ("IND", "India (IND)"),
        ("IDN", "Indonesia (IDN)"),
        ("IRN", "Iran (Islamic Republic of) (IRN)"),
        ("IRQ", "Iraq (IRQ)"),
        ("IRL", "Ireland (IRL)"),
        ("IMN", "Isle of Man (IMN)"),
        ("ISR", "Israel (ISR)"),
        ("ITA", "Italy (ITA)"),
        ("JAM", "Jamaica (JAM)"),
        ("JPN", "Japan (JPN)"),
        ("JEY", "Jersey (JEY)"),
        ("JOR", "Jordan (JOR)"),
        ("KAZ", "Kazakhstan (KAZ)"),
        ("KEN", "Kenya (KEN)"),
        ("KIR", "Kiribati (KIR)"),
        ("PRK", "Korea (the Democratic People's Republic of) (PRK)"),
        ("KOR", "Korea (the Republic of) (KOR)"),
        ("KWT", "Kuwait (KWT)"),
        ("KGZ", "Kyrgyzstan (KGZ)"),
        ("LAO", "Lao People's Democratic Republic (the) (LAO)"),
        ("LVA", "Latvia (LVA)"),
        ("LBN", "Lebanon (LBN)"),
        ("LSO", "Lesotho (LSO)"),
        ("LBR", "Liberia (LBR)"),
        ("LBY", "Libya (LBY)"),
        ("LIE", "Liechtenstein (LIE)"),
        ("LTU", "Lithuania (LTU)"),
        ("LUX", "Luxembourg (LUX)"),
        ("MAC", "Macao (MAC)"),
        ("MKD", "North Macedonia (MKD)"),
        ("MDG", "Madagascar (MDG)"),
        ("MWI", "Malawi (MWI)"),
        ("MYS", "Malaysia (MYS)"),
        ("MDV", "Maldives (MDV)"),
        ("MLI", "Mali (MLI)"),
        ("MLT", "Malta (MLT)"),
        ("MHL", "Marshall Islands (the) (MHL)"),
        ("MTQ", "Martinique (MTQ)"),
        ("MRT", "Mauritania (MRT)"),
        ("MUS", "Mauritius (MUS)"),
        ("MYT", "Mayotte (MYT)"),
        ("MEX", "Mexico (MEX)"),
        ("FSM", "Micronesia (Federated States of) (FSM)"),
        ("MDA", "Moldova (the Republic of) (MDA)"),
        ("MCO", "Monaco (MCO)"),
        ("MNG", "Mongolia (MNG)"),
        ("MNE", "Montenegro (MNE)"),
        ("MSR", "Montserrat (MSR)"),
        ("MAR", "Morocco (MAR)"),
        ("MOZ", "Mozambique (MOZ)"),
        ("MMR", "Myanmar (MMR)"),
        ("NAM", "Namibia (NAM)"),
        ("NRU", "Nauru (NRU)"),
        ("NPL", "Nepal (NPL)"),
        ("NLD", "Netherlands (the) (NLD)"),
        ("NCL", "New Caledonia (NCL)"),
        ("NZL", "New Zealand (NZL)"),
        ("NIC", "Nicaragua (NIC)"),
        ("NER", "Niger (the) (NER)"),
        ("NGA", "Nigeria (NGA)"),
        ("NIU", "Niue (NIU)"),
        ("NFK", "Norfolk Island (NFK)"),
        ("MNP", "Northern Mariana Islands (the) (MNP)"),
        ("NOR", "Norway (NOR)"),
        ("OMN", "Oman (OMN)"),
        ("PAK", "Pakistan (PAK)"),
        ("PLW", "Palau (PLW)"),
        ("PSE", "Palestine, State of (PSE)"),
        ("PAN", "Panama (PAN)"),
        ("PNG", "Papua New Guinea (PNG)"),
        ("PRY", "Paraguay (PRY)"),
        ("PER", "Peru (PER)"),
        ("PHL", "Philippines (the) (PHL)"),
        ("PCN", "Pitcairn (PCN)"),
        ("POL", "Poland (POL)"),
        ("PRT", "Portugal (PRT)"),
        ("PRI", "Puerto Rico (PRI)"),
        ("QAT", "Qatar (QAT)"),
        ("REU", "Réunion (REU)"),
        ("ROU", "Romania (ROU)"),
        ("RUS", "Russian Federation (the) (RUS)"),
        ("RWA", "Rwanda (RWA)"),
        ("BLM", "Saint Barthélemy (BLM)"),
        ("SHN", "Saint Helena, Ascension and Tristan da Cunha (SHN)"),
        ("KNA", "Saint Kitts and Nevis (KNA)"),
        ("LCA", "Saint Lucia (LCA)"),
        ("MAF", "Saint Martin (French part) (MAF)"),
        ("SPM", "Saint Pierre and Miquelon (SPM)"),
        ("VCT", "Saint Vincent and the Grenadines (VCT)"),
        ("WSM", "Samoa (WSM)"),
        ("SMR", "San Marino (SMR)"),
        ("STP", "Sao Tome and Principe (STP)"),
        ("SAU", "Saudi Arabia (SAU)"),
        ("SEN", "Senegal (SEN)"),
        ("SRB", "Serbia (SRB)"),
        ("SYC", "Seychelles (SYC)"),
        ("SLE", "Sierra Leone (SLE)"),
        ("SGP", "Singapore (SGP)"),
        ("SXM", "Sint Maarten (Dutch part) (SXM)"),
        ("SVK", "Slovakia (SVK)"),
        ("SVN", "Slovenia (SVN)"),
        ("SLB", "Solomon Islands (SLB)"),
        ("SOM", "Somalia (SOM)"),
        ("ZAF", "South Africa (ZAF)"),
        ("SGS", "South Georgia and the South Sandwich Islands (SGS)"),
        ("SSD", "South Sudan (SSD)"),
        ("ESP", "Spain (ESP)"),
        ("LKA", "Sri Lanka (LKA)"),
        ("SDN", "Sudan (the) (SDN)"),
        ("SUR", "Suriname (SUR)"),
        ("SJM", "Svalbard and Jan Mayen (SJM)"),
        ("SWE", "Sweden (SWE)"),
        ("CHE", "Switzerland (CHE)"),
        ("SYR", "Syrian Arab Republic (the) (SYR)"),
        ("TWN", "Taiwan (Province of China) (TWN)"),
        ("TJK", "Tajikistan (TJK)"),
        ("TZA", "Tanzania, United Republic of (TZA)"),
        ("THA", "Thailand (THA)"),
        ("TLS", "Timor-Leste (TLS)"),
        ("TGO", "Togo (TGO)"),
        ("TKL", "Tokelau (TKL)"),
        ("TON", "Tonga (TON)"),
        ("TTO", "Trinidad and Tobago (TTO)"),
        ("TUN", "Tunisia (TUN)"),
        ("TUR", "Turkey (TUR)"),
        ("TKM", "Turkmenistan (TKM)"),
        ("TCA", "Turks and Caicos Islands (the) (TCA)"),
        ("TUV", "Tuvalu (TUV)"),
        ("UGA", "Uganda (UGA)"),
        ("UKR", "Ukraine (UKR)"),
        ("ARE", "United Arab Emirates (the) (ARE)"),
        ("GBR", "United Kingdom of Great Britain and Northern Ireland (the) (GBR)"),
        ("UMI", "United States Minor Outlying Islands (the) (UMI)"),
        ("USA", "United States of America (USA)"),
        ("URY", "Uruguay (URY)"),
        ("UZB", "Uzbekistan (UZB)"),
        ("VUT", "Vanuatu (VUT)"),
        ("VEN", "Venezuela (Bolivarian Republic of) (VEN)"),
        ("VNM", "Viet Nam (VNM)"),
        ("VGB", "Virgin Islands (British) (VGB)"),
        ("VIR", "Virgin Islands (U.S.) (VIR)"),
        ("WLF", "Wallis and Futuna (WLF)"),
        ("ESH", "Western Sahara (ESH)"),
        ("YEM", "Yemen (YEM)"),
        ("ZMB", "Zambia (ZMB)"),
        ("ZWE", "Zimbabwe (ZWE)"),
    ],
    "country_codes": [
        ("MEX", "Mexico"),
    ],
    "currency_code_all": [
        ("AED", "United Arab Emirates dirham (AED)"),
        ("AFN", "Afghan afghani (AFN)"),
        ("ALL", "Albanian lek (ALL)"),
        ("AMD", "Armenian dram (AMD)"),
        ("ANG", "Netherlands Antillean guilder (ANG)"),
        ("AOA", "Angolan kwanza (AOA)"),
        ("ARS", "Argentine peso (ARS)"),
        ("AUD", "Australian dollar (AUD)"),
        ("AWG", "Aruban florin (AWG)"),
        ("AZN", "Azerbaijani manat (AZN)"),
        ("BAM", "Bosnia and Herzegovina convertible mark (BAM)"),
        ("BBD", "Barbados dollar (BBD)"),
        ("BDT", "Bangladeshi taka (BDT)"),
        ("BGN", "Bulgarian lev (BGN)"),
        ("BHD", "Bahraini dinar (BHD)"),
        ("BIF", "Burundian franc (BIF)"),
        ("BMD", "Bermudian dollar (BMD)"),
        ("BND", "Brunei dollar (BND)"),
        ("BOB", "Boliviano (BOB)"),
        ("BOV", "Bolivian Mvdol (BOV)"),
        ("BRL", "Brazilian real (BRL)"),
        ("BSD", "Bahamian dollar (BSD)"),
        ("BTN", "Bhutanese ngultrum (BTN)"),
        ("BWP", "Botswana pula (BWP)"),
        ("BYN", "Belarusian ruble (BYN)"),
        ("BZD", "Belize dollar (BZD)"),
        ("CAD", "Canadian dollar (CAD)"),
        ("CDF", "Congolese franc (CDF)"),
        ("CHE", "WIR euro (CHE)"),
        ("CHF", "Swiss franc (CHF)"),
        ("CHW", "WIR franc (CHW)"),
        ("CLF", "Unidad de Fomento (CLF)"),
        ("CLP", "Chilean peso (CLP)"),
        ("CNY", "Chinese yuan (CNY)"),
        ("COP", "Colombian peso (COP)"),
        ("COU", "Unidad de Valor Real (COU)"),
        ("CRC", "Costa Rican colon (CRC)"),
        ("CUC", "Cuban convertible peso (CUC)"),
        ("CUP", "Cuban peso (CUP)"),
        ("CVE", "Cape Verdean escudo (CVE)"),
        ("CZK", "Czech koruna (CZK)"),
        ("DJF", "Djiboutian franc (DJF)"),
        ("DKK", "Danish krone (DKK)"),
        ("DOP", "Dominican peso (DOP)"),
        ("DZD", "Algerian dinar (DZD)"),
        ("EGP", "Egyptian pound (EGP)"),
        ("ERN", "Eritrean nakfa (ERN)"),
        ("ETB", "Ethiopian birr (ETB)"),
        ("EUR", "Euro (EUR)"),
        ("FJD", "Fiji dollar (FJD)"),
        ("FKP", "Falkland Islands pound (FKP)"),
        ("GBP", "Pound sterling (GBP)"),
        ("GEL", "Georgian lari (GEL)"),
        ("GHS", "Ghanaian cedi (GHS)"),
        ("GIP", "Gibraltar pound (GIP)"),
        ("GMD", "Gambian dalasi (GMD)"),
        ("GNF", "Guinean franc (GNF)"),
        ("GTQ", "Guatemalan quetzal (GTQ)"),
        ("GYD", "Guyanese dollar (GYD)"),
        ("HKD", "Hong Kong dollar (HKD)"),
        ("HNL", "Honduran lempira (HNL)"),
        ("HRK", "Croatian kuna (HRK)"),
        ("HTG", "Haitian gourde (HTG)"),
        ("HUF", "Hungarian forint (HUF)"),
        ("IDR", "Indonesian rupiah (IDR)"),
        ("ILS", "Israeli new shekel (ILS)"),
        ("INR", "Indian rupee (INR)"),
        ("IQD", "Iraqi dinar (IQD)"),
        ("IRR", "Iranian rial (IRR)"),
        ("ISK", "Icelandic króna (ISK)"),
        ("JMD", "Jamaican dollar (JMD)"),
        ("JOD", "Jordanian dinar (JOD)"),
        ("JPY", "Japanese yen (JPY)"),
        ("KES", "Kenyan shilling (KES)"),
        ("KGS", "Kyrgyzstani som (KGS)"),
        ("KHR", "Cambodian riel (KHR)"),
        ("KMF", "Comoro franc (KMF)"),
        ("KPW", "North Korean won (KPW)"),
        ("KRW", "South Korean won (KRW)"),
        ("KWD", "Kuwaiti dinar (KWD)"),
        ("KYD", "Cayman Islands dollar (KYD)"),
        ("KZT", "Kazakhstani tenge (KZT)"),
        ("LAK", "Lao kip (LAK)"),
        ("LBP", "Lebanese pound (LBP)"),
        ("LKR", "Sri Lankan rupee (LKR)"),
        ("LRD", "Liberian dollar (LRD)"),
        ("LSL", "Lesotho loti (LSL)"),
        ("LYD", "Libyan dinar (LYD)"),
        ("MAD", "Moroccan dirham (MAD)"),
        ("MDL", "Moldovan leu (MDL)"),
        ("MGA", "Malagasy ariary (MGA)"),
        ("MKD", "Macedonian denar (MKD)"),
        ("MMK", "Myanmar kyat (MMK)"),
        ("MNT", "Mongolian tögrög (MNT)"),
        ("MOP", "Macanese pataca (MOP)"),
        ("MRU", "Mauritanian ouguiya (MRU)"),
        ("MUR", "Mauritian rupee (MUR)"),
        ("MVR", "Maldivian rufiyaa (MVR)"),
        ("MWK", "Malawian kwacha (MWK)"),
        ("MXN", "Mexican peso (MXN)"),
        ("MXV", "Mexican Unidad de Inversion (MXV)"),
        ("MYR", "Malaysian ringgit (MYR)"),
        ("MZN", "Mozambican metical (MZN)"),
        ("NAD", "Namibian dollar (NAD)"),
        ("NGN", "Nigerian naira (NGN)"),
        ("NIO", "Nicaraguan córdoba (NIO)"),
        ("NOK", "Norwegian krone (NOK)"),
        ("NPR", "Nepalese rupee (NPR)"),
        ("NZD", "New Zealand dollar (NZD)"),
        ("OMR", "Omani rial (OMR)"),
        ("PAB", "Panamanian balboa (PAB)"),
        ("PEN", "Peruvian sol (PEN)"),
        ("PGK", "Papua New Guinean kina (PGK)"),
        ("PHP", "Philippine peso (PHP)"),
        ("PKR", "Pakistani rupee (PKR)"),
        ("PLN", "Polish złoty (PLN)"),
        ("PYG", "Paraguayan guaraní (PYG)"),
        ("QAR", "Qatari riyal (QAR)"),
        ("RON", "Romanian leu (RON)"),
        ("RSD", "Serbian dinar (RSD)"),
        ("RUB", "Russian ruble (RUB)"),
        ("RWF", "Rwandan franc (RWF)"),
        ("SAR", "Saudi riyal (SAR)"),
        ("SBD", "Solomon Islands dollar (SBD)"),
        ("SCR", "Seychelles rupee (SCR)"),
        ("SDG", "Sudanese pound (SDG)"),
        ("SEK", "Swedish krona (SEK)"),
        ("SGD", "Singapore dollar (SGD)"),
        ("SHP", "Saint Helena pound (SHP)"),
        ("SLL", "Sierra Leonean leone (SLL)"),
        ("SOS", "Somali shilling (SOS)"),
        ("SRD", "Surinamese dollar (SRD)"),
        ("SSP", "South Sudanese pound (SSP)"),
        ("STN", "São Tomé and Príncipe dobra (STN)"),
        ("SVC", "Salvadoran colón (SVC)"),
        ("SYP", "Syrian pound (SYP)"),
        ("SZL", "Swazi lilangeni (SZL)"),
        ("THB", "Thai baht (THB)"),
        ("TJS", "Tajikistani somoni (TJS)"),
        ("TMT", "Turkmenistan manat (TMT)"),
        ("TND", "Tunisian dinar (TND)"),
        ("TOP", "Tongan paʻanga (TOP)"),
        ("TRY", "Turkish lira (TRY)"),
        ("TTD", "Trinidad and Tobago dollar (TTD)"),
        ("TWD", "New Taiwan dollar (TWD)"),
        ("TZS", "Tanzanian shilling (TZS)"),
        ("UAH", "Ukrainian hryvnia (UAH)"),
        ("UGX", "Ugandan shilling (UGX)"),
        ("USD", "United States dollar (USD)"),
        ("USN", "United States dollar (next day) (USN)"),
        ("UYI", "Uruguay Peso en Unidades Indexadas (UYI)"),
        ("UYU", "Uruguayan peso (UYU)"),
        ("UYW", "Unidad previsional (UYW)"),
        ("UZS", "Uzbekistan som (UZS)"),
        ("VES", "Venezuelan bolívar soberano (VES)"),
        ("VND", "Vietnamese đồng (VND)"),
        ("VUV", "Vanuatu vatu (VUV)"),
        ("WST", "Samoan tala (WST)"),
        ("XAF", "CFA franc BEAC (XAF)"),
        ("XAG", "Silver (one troy ounce) (XAG)"),
        ("XAU", "Gold (one troy ounce) (XAU)"),
        ("XBA", "European Composite Unit (XBA)"),
        ("XBB", "European Monetary Unit (XBB)"),
        ("XBC", "European Unit of Account 9 (XBC)"),
        ("XBD", "European Unit of Account 17 (XBD)"),
        ("XCD", "East Caribbean dollar (XCD)"),
        ("XDR", "Special drawing rights (XDR)"),
        ("XOF", "CFA franc BCEAO (XOF)"),
        ("XPD", "Palladium (one troy ounce) (XPD)"),
        ("XPF", "CFP franc (XPF)"),
        ("XPT", "Platinum (one troy ounce) (XPT)"),
        ("XSU", "SUCRE (XSU)"),
        ("XTS", "Code reserved for testing (XTS)"),
        ("XUA", "ADB Unit of Account (XUA)"),
        ("YER", "Yemeni rial (YER)"),
        ("ZAR", "South African rand (ZAR)"),
        ("ZMW", "Zambian kwacha (ZMW)"),
        ("ZWL", "Zimbabwean dollar (ZWL)"),
        ("XXX", "No currency (XXX)"),
    ],
    "demographic_type": [
        ("M", "Merchant"),
        ("S", "Store"),
        ("C", "Chain"),
    ],
    "email_type": [
        ("P", "Personal"),
        ("W", "Work"),
        ("1", "Additional 1"),
        ("2", "Additional 2"),
        ("3", "Additional 3"),
        ("4", "Additional 4"),
    ],
    "entity_status": [
        ("A", "Active"),
        ("I", "Inactive"),
    ],
    "entry_type": [
        ("0", "UNKNOWN(\"0\")"),
        ("1", "MANUAL_KEY_ENTRY(\"1\")"),
        ("2", "MOTO(\"2\")"),
        ("3", "ECOMM(\"3\")"),
        ("4", "MAG_CVV_NOT_POSSIBLE(4)"),
        ("5", "OPTICAL_CODE(5)"),
        ("6", "ICC(6)"),
        ("7", "STORE_VALUE_PRE_REGISTERED(7)"),
        ("8", "CONTACT_LESS_ICC(8)"),
        ("9", "COF(9)"),
        ("A", "COF_TOKEN(A)"),
        ("B", "MAG(B)"),
        ("C", "CONTACT_LESS_MAG(C)"),
        ("D", "FALLBACK(D)"),
        ("E", "ICC_INVALID_CVV_I_CVV(E)"),
        ("F", "WALLET_CONTACT_LESS_ICC(F)"),
        ("G", "WALLET_CONTACT_MST(G)"),
        ("H", "WALLET_CONTACT_LESS_MAG_STRIPE(H)"),
        ("I", "CHEQUE(I)"),
    ],
    "file_format": [
        (".txt", "Text File"),
        (".pem", "PEM File"),
        (".csv", "CSV File"),
        (".pdf", "PDF File"),
        (".xls", "Excel File"),
        (".doc", "Document File"),
    ],
    "international_applied": [
        ("I", "International"),
        ("D", "Domestic"),
        ("B", "Both"),
    ],
    "iso_network_type": [
        ("VI", "VISA VIP"),
        ("MC", "MasterCard"),
        ("PP", "PROSA POS"),
        ("PA", "PROSA ATM"),
        ("HT", "Host Terminal"),
        ("CUSTOM", "Custom Network"),
    ],
    "language": [
        ("ES", "Español"),
        ("EN", "English"),
    ],
    "latitude_direction": [
        ("N", "North (N)"),
        ("S", "South (S)"),
    ],
    "limit_type": [
        ("N", "NO_SPECIFIC(N)"),
        ("R", "RETAIL(R)"),
        ("C", "CASH(C)"),
        ("O", "OTC(O)"),
        ("A", "ATM(A)"),
        ("Q", "QUASI_CASH(Q)"),
        ("D", "DEPOSITS(D)"),
        ("RE", "RECHARGE(RE)"),
        ("CT", "CONTACTLESS(CT)"),
        ("NONE", "No Limit"),
    ],
    "location_identifiers": [
        ("ID_CADENA", "ID Cadena"),
        ("ID_PLAZA", "ID Plaza"),
    ],
    "longitude_direction": [
        ("E", "East (E)"),
        ("W", "West (W)"),
    ],
    "phone_country": [
        ("+52", "MEXICO"),
        ("+1", "USA"),
    ],
    "phone_type": [
        ("PL", "Personal Landline"),
        ("PM", "Personal Mobile"),
        ("WL", "Work Landline"),
        ("WM", "Work Mobile"),
        ("1", "Additional 1"),
        ("2", "Additional 2"),
        ("3", "Additional 3"),
        ("4", "Additional 4"),
    ],
    "purchase_type": [
        ("G", "GROCERIES(G)"),
        ("RP", "RISKY_PURCHASE(RP)"),
        ("RA", "RESTRICTED_ADULTS(RA)"),
        ("GA", "GAMBLING(GA)"),
        ("RS", "RESTAURANT(RS)"),
        ("AR", "AUTO_RENTAL(AR)"),
        ("LG", "LODGING(LG)"),
        ("HC", "HEALTH_CARE(HC)"),
        ("AI", "AIRLINE (AI)"),
        ("CC", "CRYPTO_CURRENCY (CC)"),
        ("O", "OTHERS (O)"),
    ],
    "rest_method": [
        ("GET", "GET - View"),
        ("POST", "POST - Add"),
        ("PUT", "PUT - Update"),
        ("DELETE", "DELETE - Delete"),
    ],
    "security_policy_blocks": [
        ("merchant-page", "merchant-page"),
        ("chain-page", "chain-page"),
        ("store-page", "store-page"),
        ("demographic-page", "demographic-page"),
        ("connector-page", "connector-page"),
        ("connector-iso-fields", "connector-iso-fields"),
        ("connector-connection", "connector-connection"),
        ("store-terminals", "store-terminals"),
        ("merchant-channels", "merchant-channels"),
        ("chain-channels", "chain-channels"),
        ("store-channels", "store-channels"),
    ],
    "security_subsystems": [
        ("switching", "Switching"),
    ],
    "security_uri_path": [
        ("/auth/merchant/v1", "/auth/merchant/v1"),
        ("/auth/chain/v1", "/auth/chain/v1"),
        ("/auth/store/v1", "/auth/store/v1"),
        ("/auth/demographic/v1", "/auth/demographic/v1"),
        ("/config/connector-properties/v1", "/config/connector-properties/v1"),
        ("/auth/connectorTable/v1", "/auth/connectorTable/v1"),
        ("/config/merchant-criteria/v1", "/config/merchant-criteria/v1"),
        ("/config/instrument-criteria/v1", "/config/instrument-criteria/v1"),
        ("/config/instrument-stat/v1", "/config/instrument-stat/v1"),
        ("/config/instrument-stat/v1/reload", "/config/instrument-stat/v1/reload"),
        ("/config/connector-config/v1", "/config/connector-config/v1"),
        ("/config/security-config/v1/load/groups", "/config/security-config/v1/load/groups"),
        ("/config/security-config/v1/load/roles", "/config/security-config/v1/load/roles"),
        ("/config/security-config/v1/load/scopes", "/config/security-config/v1/load/scopes"),
        ("/config/security-config/v1/load/policy", "/config/security-config/v1/load/policy"),
        ("/config/security-config/v1/groups", "/config/security-config/v1/groups"),
        ("/config/security-config/v1/jwt", "/config/security-config/v1/jwt"),
        ("/config/security-config/v1/jwt/roles", "/config/security-config/v1/jwt/roles"),
        ("/config/security-config/v1/jwt/scopes", "/config/security-config/v1/jwt/scopes"),
        ("/config/security-config/v1/jwt/groups", "/config/security-config/v1/jwt/groups"),
        ("/config/security-config/v1/roles", "/config/security-config/v1/roles"),
        ("/config/security-config/v1/scopes", "/config/security-config/v1/scopes"),
        ("/config/security-config/v1/policy", "/config/security-config/v1/policy"),
        ("/config/security-config/v1/getRequestPolicies", "/config/security-config/v1/getRequestPolicies"),
        ("/config/secrets/v1", "/config/secrets/v1"),
        ("/config/secrets/v1/connectorUserIdPassword", "/config/secrets/v1/connectorUserIdPassword"),
        ("/config/secrets/v1/fileWithPassword", "/config/secrets/v1/fileWithPassword"),
        ("/config/secrets/v1/file", "/config/secrets/v1/file"),
        ("/config/s3-upload/v1", "/config/s3-upload/v1"),
    ],
    "serialization_type": [
        ("FIXED", "FIXED"),
        ("JSON", "JSON"),
        ("XML", "XML"),
        ("CSV", "CSV"),
        ("BINARY", "BINARY"),
        ("PROTOBUF", "PROTOBUF"),
        ("ISO8583", "ISO8583"),
    ],
    "session_timeout_minute": [
        ("5", "session-timeout-minute"),
    ],
    "state": [
        ("AGU", "Aguascalientes"),
        ("BCN", "Baja California"),
        ("BCS", "Baja California Sur"),
        ("CAM", "Campeche"),
        ("CHP", "Chiapas"),
        ("CHH", "Chihuahua"),
        ("COA", "Coahuila de Zaragoza"),
        ("COL", "Colima"),
        ("CMX", "Ciudad de México"),
        ("DUR", "Durango"),
        ("GUA", "Guanajuato"),
        ("GRO", "Guerrero"),
        ("HID", "Hidalgo"),
        ("JAL", "Jalisco"),
        ("MEX", "Estado de México"),
        ("MIC", "Michoacán de Ocampo"),
        ("MOR", "Morelos"),
        ("NAY", "Nayarit"),
        ("NLE", "Nuevo León"),
        ("OAX", "Oaxaca"),
        ("PUE", "Puebla"),
        ("QUE", "Querétaro"),
        ("ROO", "Quintana Roo"),
        ("SLP", "San Luis Potosí"),
        ("SIN", "Sinaloa"),
        ("SON", "Sonora"),
        ("TAB", "Tabasco"),
        ("TAM", "Tamaulipas"),
        ("TLA", "Tlaxcala"),
        ("VER", "Veracruz de Ignacio de la Llave"),
        ("YUC", "Yucatán"),
        ("ZAC", "Zacatecas"),
    ],
    "table_type": [
        ("CONNECTOR", "Connector"),
    ],
    "temp_perm": [
        ("TEMPORARY", "TEMPORARY"),
        ("PERMANENT", "PERMANENT"),
    ],
    "terminal_status": [
        ("ACTIVE", "Active"),
        ("INACTIVE", "Inactive"),
    ],
    "terminal_type": [
        ("POS", "POS"),
        ("KIOSK", "KIOSK"),
    ],
    "time_unit": [
        ("SECOND", "SECOND"),
        ("MINUTE", "MINUTE"),
        ("HOUR", "HOUR"),
        ("DAY", "DAY"),
        ("WEEK", "WEEK"),
        ("MONTH", "MONTH"),
        ("YEAR", "YEAR"),
    ],
    "time_zone": [
        ("UTC", "Coordinated Universal Time"),
        ("GMT", "Greenwich Mean Time"),
        ("America/Mexico_City", "America/Mexico_City"),
        ("America/Tijuana", "America/Tijuana"),
        ("America/Cancun", "America/Cancun"),
        ("America/Monterrey", "America/Monterrey"),
    ],
    "transaction_type": [
        ("0", "PURCHASE(\"0\")"),
        ("1", "QUASI_CASH(\"1\")"),
        ("2", "BALANCE_INQUIRIES(\"2\")"),
        ("3", "PREPAID_LOAD(\"3\")"),
        ("4", "PREPAID_ACTIVATION(\"4\")"),
        ("5", "CARD_ACTIVATION(\"5\")"),
        ("6", "READY_LINK_LOAD(\"6\")"),
        ("7", "BILL_PAYMENT(\"7\")"),
        ("8", "PIN_CHANGE(\"8\")"),
        ("9", "PIN_UNBLOCK(\"9\")"),
        ("A", "PRIVATE_LABEL_PREPAID(A)"),
        ("B", "ELIGIBILITY_ENQUIRY(B)"),
        ("C", "PAYMENT(C)"),
        ("D", "CREDIT_VOUCHER(D)"),
        ("E", "MERCHANDISE_RETURN(E)"),
        ("F", "OCT(F)"),
        ("G", "CASH(G)"),
        ("H", "ACCOUNT_FUND_TRANSACTION(H)"),
        ("I", "ACCOUNT_VERIFICATION(I)"),
        ("J", "TOKEN_COMPLETION_NOTIFICATION(J)"),
        ("K", "TOKEN_ACTIVATION_REQUEST(K)"),
        ("L", "ACTIVATION_CODE_NOTIFICATION(L)"),
        ("M", "TOKEN_EVENT_NOTIFICATION(M)"),
        ("N", "TOKEN_ELIGIBILITY(N)"),
        ("O", "RECHARGE(O)"),
        ("P", "DEPOSITS(P)"),
        ("OTHER", "Other"),
        ("U", "UNKNOWN(U)"),
    ],
}


def _norm_key(s: str) -> str:
    text = unicodedata.normalize("NFKD", str(s))
    text = "".join(c for c in text if not unicodedata.combining(c))
    return text.lower().strip()


def _build_lookups() -> tuple[Dict[str, Dict[str, str]], Dict[str, FrozenSet[str]]]:
    lookup: Dict[str, Dict[str, str]] = {}
    canonical: Dict[str, FrozenSet[str]] = {}
    for element, pairs in ELEMENT_ENTRIES.items():
        m: Dict[str, str] = {}
        codes: set[str] = set()
        for code, display in pairs:
            codes.add(code)
            m[_norm_key(code)] = code
            if display:
                m[_norm_key(display)] = code
        lookup[element] = m
        canonical[element] = frozenset(codes)
    return lookup, canonical


ELEMENT_LOOKUP, CANONICAL_CODES = _build_lookups()


def map_element_value(element: str, value: Any) -> Any:
    """Map Excel/UI text to canonical code; return original if unknown."""
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    m = ELEMENT_LOOKUP.get(element)
    if not m:
        return value
    norm = _norm_key(text)
    if norm in m:
        return m[norm]
    upper = text.upper()
    codes = CANONICAL_CODES.get(element, frozenset())
    if upper in codes:
        return upper
    if text in codes:
        return text
    return value
